services:
  llm-tool-whisper:
    image: ghcr.io/starlight02/llm-tool-whisper:latest
    ports:
      - "8787:8787"
    volumes:
      - ./config.toml:/etc/llm-tool-whisper/config.toml:ro
    restart: unless-stopped
